# Generated by Django 5.0.2 on 2024-02-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_tp_created_at_otptoken_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('result', models.CharField(blank=True, choices=[('Safe', 'Safe'), ('Phishing', 'Phishing')], max_length=10, null=True)),
            ],
        ),
    ]
