# Generated by Django 5.0.2 on 2024-03-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='generated_by_input_url',
            field=models.BooleanField(default=False),
        ),
    ]
