# Generated by Django 5.0.2 on 2024-03-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_url_generated_by_input_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='generated_by_input_url',
        ),
    ]
