# Generated by Django 5.0.2 on 2024-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_url_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('phish_url', models.URLField(blank=True, null=True)),
                ('phish_result', models.CharField(blank=True, max_length=10, null=True)),
                ('onion_url', models.URLField(blank=True, null=True)),
                ('onion_result', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('Safe', 'Safe'), ('Phishing', 'Phishing')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
