name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (Updated to actions/checkout@v4)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (Updated to actions/setup-python@v5)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Set up Node.js (If applicable to your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add any other dependency installation if needed
          
      # Step 5: Run tests (Make sure the test command matches your project)
      - name: Run tests
        run: |
          python -m unittest discover tests/
          # Or use pytest or another test runner if applicable

      # Step 6: Deploy or additional steps (if any)
      # - name: Deploy code
      #   run: |
      #     ./deploy_script.sh

